skinparam defaultFontName "Microsoft YaHei"
skinparam defaultMonospacedFontName "Microsoft YaHei"
skinparam titleFontName "Microsoft YaHei"
skinparam captionFontName "Microsoft YaHei"
skinparam noteFontName "Microsoft YaHei"
skinparam classFontName "Microsoft YaHei"
skinparam packageFontName "Microsoft YaHei"
skinparam componentFontName "Microsoft YaHei"
skinparam usecaseFontName "Microsoft YaHei"
skinparam activityFontName "Microsoft YaHei"
skinparam sequenceFontName "Microsoft YaHei"
skinparam stateFontName "Microsoft YaHei"
skinparam legendFontName "Microsoft YaHei"

