@startuml
!include _skin.iuml
package Frontend {
  [Pages]
  [Components]
  [Stores]
}
package Backend {
  [API]
  [Services]
  [Repositories]
  [Models]
}
package Database {
  [PostgreSQL]
}
Frontend --> Backend
Backend --> Database
@enduml

